services:
  - type: web
    name: tg-bot
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false  # مقدار را بعداً در داشبورد می‌گذاری
